# -*- coding: utf-8 -*-
"""chris_lee_HW_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NeLQIoqWk65c4Ulj0mZxMipT6zJci0Sp
"""

# import all necessary libraries here

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import plot_confusion_matrix

df = pd.read_csv('Titanic.csv')

df.head()

df.shape

df.info()

df.describe()

try:
  df = df.drop('Passenger', axis=1)
except:
  pass

df.isnull().sum()

#there are no missing values

sns.countplot(x='Class', data=df)

sns.countplot(x='Sex', data=df)

sns.countplot(x='Age', data=df)

sns.countplot(x='Survived', data=df)

df2 = pd.get_dummies(df, columns=['Class', 'Sex', 'Age'])

df2

X = df2.drop(['Survived'], axis=1)

y = df2['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2020)

logreg = LogisticRegression()

logreg.fit(X_train, y_train)

outcomes = logreg.predict(X_test)

survival = accuracy_score(y_test, outcomes)

pred = cross_val_predict(logreg, X_train, y_train, cv=3)
confusion_matrix(y_train, pred)
plot_confusion_matrix(logreg, X_test, y_test)

logreg.predict([[0,0,1,0,0,1,1,0]])

logreg.predict_proba([[0,0,1,0,0,1,1,0]])